# Open PR -> deploy to Maven Central Staging
name: Deploy to Maven Central Staging

on:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]

jobs:
  deploy-mavencentral:
    runs-on: macos-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          distribution: temurin
          java-version: 17
      - uses: ./.github/actions/gradle-cache
      - name: Set Staging version
        run: |
          sed -i "" -E "s/^kottage = \"(.*)\"$/kottage = \"\\1-pr${{ github.event.pull_request.number }}.${{ github.run_number }}.${{ github.run_attempt }}\"/g" gradle/libs.versions.toml
          grep "^kottage" gradle/libs.versions.toml
      - name: Deploy to Maven Central
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME_TOKEN }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD_TOKEN }}
          SIGNING_PGP_KEY: ${{ secrets.SIGNING_PGP_KEY }}
          SIGNING_PGP_PASSWORD: ${{ secrets.SIGNING_PGP_PASSWORD }}
        run: |
          # kottageではstagingリポジトリのcloseがタイムアウトするためcloseしない
          # ./gradlew publishToSonatype closeSonatypeStagingRepository
          ./gradlew publishToSonatype
